### ISSUE TITLE
[BE] Search Story

### ISSUE THREAD

**Issue by rorre** [ReadVerseRPL/ReadVerse#10]

**Comment by yudiptr** [comment]
fitur ini dapat memungkinkan seorang pengguna untuk mencari cerita yang ingin dibaca olehnya. Fitur ini bertujuan agar pembaca tidak perlu mencari satu per satu cerita yang tersedia pada aplikasi ReadVerse sehingga lebih efisien dalam waktu.

**Comment by yudiptr** [comment]
User story :
* Sebagai seorang pengguna dapat mencari cerita yang ingin mereka baca langsung pada kolom search bar

Acceptance
* Pengguna dapat melakukan pencarian terhadap suatu cerita

**Comment by yudiptr** [comment]
Task-task
* Mengimplementasikan fitur untuk melakukan pencarian terhadap suatu cerita
* Mengembangkan logika untuk mencari suatu cerita berdasarkan keyword yang ditulis oleh pengguna
