### ISSUE TITLE
[BE] Delete Story

### ISSUE THREAD

**Issue by rorre** [ReadVerseRPL/ReadVerse#12]

**Comment by swastikanata** [comment]
Fitur ini memungkinkan penulis dan admin untuk menghapus sebuah cerita. Penulis dapat menghapus cerita yang ditulis oleh dirinya sendiri. Admin dapat menghapus cerita yang melanggar syarat dan ketentuan platform. Fitur ini bertujuan sebagai salah satu sarana penulis dalam mengelola konten miliknya dan sarana admin dalam menjaga akuntabilitas dari platform ReadVerse.

**Comment by swastikanata** [comment]
User Story:
- Sebagai seorang penulis, saya ingin dapat menghapus cerita yang sebelumnya sudah saya tulis sendiri sebagai.
- Sebagai seorang admin, saya ingin dapat menghapus cerita yang melanggar syarat dan ketentuan platform agar platform ini dapat digunakan dengan nyaman oleh semua pihak pengguna.

Acceptance Criteria

- Admin dan pembaca harus dapat melihat cerita-cerita yang ada di platform
- Penulis harus dapat menghapus cerita yang ditulisnya sendiri
- Admin harus dapat menghapus cerita yang dibuat oleh penulis

**Comment by swastikanata** [comment]
Task-Task

- Menambahkan fitur untuk menghapus cerita dalam database.
- Mengimplementasikan logika untuk penghapusan cerita oleh penulis dan admin.

**Comment by rorre** [comment]
Closed by https://github.com/ReadVerseRPL/ReadVerse/pull/24
