### ISSUE TITLE
[BE] GET Profile

### ISSUE THREAD

**Issue by rorre** [ReadVerseRPL/ReadVerse#13]

**Comment by swastikanata** [comment]
Fitur ini memungkinkan pengguna untuk melihat profil, baik profil miliknya sendiri maupun profil pengguna lain. Fitur ini bertujuan sebagai salah satu bentuk interaksi pengguna dan sarana untuk melihat siapa saja orang yang menggunakan platform ReadVerse.

**Comment by swastikanata** [comment]
User Story:

- Sebagai seorang pengguna, saya ingin dapat melihat profil dan mengenal pengguna yang menggunakan platform ini seperti saya. 
- Sebagai seroang pengguna, tentunya saya juga ingin dapat melihat profil diri saya sendiri

Acceptance Criteria
- Pengguna dapat melihat halaman profil dirinya sendiri.
- Pengguna harus dapat melihat halaman profil dari seorang pengguna lain ketika pengguna tersebut terlihat di informasi cerita maupun di komentar.

**Comment by swastikanata** [comment]
Task - task
- Menambahkan fitur untuk mendapatkan data profil pengguna dari database.
- Mengimplementasikan logika untuk melihat profil pengguna.

**Comment by rorre** [comment]
Fixed by https://github.com/ReadVerseRPL/ReadVerse/pull/24
