### ISSUE TITLE
[BE] Delete Comment

### ISSUE THREAD

**Issue by rorre** [ReadVerseRPL/ReadVerse#14]

**Comment by swastikanata** [comment]
Fitur ini memungkinkan admin untuk melihat daftar komentar yang ada pada cerita. Selain itu, admin juga dapat menghapus komentar yang melanggar syarat dan ketentuan platform. Fitur ini bertujuan sebagai salah satu sarana admin dalam menjaga akuntabilitas dari platform ReadVerse.

**Comment by swastikanata** [comment]
User Story:

- Sebagai seorang admin, saya ingin dapat menghapus komentar pembaca yang melanggar syarat dan ketentuan platform agar platform ini dapat digunakan dengan nyaman oleh semua pihak pengguna

Acceptance Criteria

- Admin harus dapat melihat komentar-komentar yang ada di suatu cerita
- Admin harus dapat menghapus komentar yang ada di suatu cerita

**Comment by swastikanata** [comment]
Task-Task

- Menambahkan fitur untuk menghapus suatu komentar untuk suatu cerita dalam database.
- Mengimplementasikan logika untuk penghapusan komentar oleh admin.

**Comment by rorre** [comment]
Fixed by https://github.com/ReadVerseRPL/ReadVerse/pull/24
