### ISSUE TITLE
[BE] GET Recently Created Stories

### ISSUE THREAD

**Issue by bryan273** [ReadVerseRPL/ReadVerse#6]
Fitur ini memungkinkan pengguna untuk melihat daftar cerita yang baru saja diterbitkan di platform. Daftar ini akan ditampilkan di halaman utama setelah pengguna melakukan login. Fitur ini bertujuan untuk memberikan akses cepat ke konten terbaru dan meningkatkan keterlibatan pengguna dengan cerita terkini.

**Comment by bryan273** [comment]
User Story

Sebagai pengguna platform menulis dan membaca cerita, Saya ingin melihat daftar cerita yang baru saja diterbitkan, Agar saya dapat dengan mudah menemukan dan membaca cerita terbaru.

Acceptance Criteria
1. Setelah login, pengguna harus bisa melihat daftar cerita yang baru saja diterbitkan di halaman utama.
2. Daftar cerita harus diperbarui secara otomatis dengan cerita terbaru.
3. Setiap item dalam daftar harus menyertakan judul cerita, nama penulis, tanggal penerbitan, dan snippet atau ringkasan singkat.

**Comment by bryan273** [comment]
Task:
1. Mengecek apakah database memiliki cerita
2. Menambahkan fungsi untuk mengambil cerita terbaru dari database.
3. Mengimplementasikan logika untuk memperbarui daftar berdasarkan waktu penerbitan.

**Comment by rorre** [comment]
Linked with https://github.com/orgs/ReadVerseRPL/projects/1/views/1?pane=issue&itemId=45784286

**Comment by rorre** [comment]
Resolved https://github.com/ReadVerseRPL/ReadVerse/commit/c60f4b649a91085c4701312cbe2bbf2e7759ed05
