### ISSUE TITLE
[BE] Update Story

### ISSUE THREAD

**Issue by bryan273** [ReadVerseRPL/ReadVerse#7]
Fitur ini memungkinkan penulis untuk melakukan update pada cerita yang telah mereka publikasikan. Penulis dapat mengedit konten cerita, judul, deskripsi, dan genre. Fitur ini bertujuan untuk memberikan fleksibilitas kepada penulis dalam memperbarui dan memperbaiki cerita mereka sesuai kebutuhan.

**Comment by bryan273** [comment]
User Story:

Sebagai penulis pada platform menulis dan membaca cerita, Saya ingin dapat mengedit cerita yang telah saya buat, Agar saya bisa memperbarui, memperbaiki, atau mengubah detail cerita sesuai dengan keinginan atau kebutuhan saya.

Acceptance Criteria
1. Penulis harus dapat mengakses opsi untuk mengedit cerita dari halaman cerita mereka.
2. Penulis harus dapat mengedit judul, konten, deskripsi, dan genre cerita.
3. Setelah selesai mengedit, penulis harus dapat menyimpan perubahan mereka.
4. Sistem harus melakukan validasi input untuk memastikan bahwa data yang diedit sesuai dengan format yang diperlukan.
5. Hanya penulis yang berhak atas cerita tersebut yang dapat melakukan edit cerita.

**Comment by bryan273** [comment]
Task-Task
1. Menambahkan fitur untuk memperbarui data cerita (judul, konten, deskripsi, genre) dalam database.
2. Mengimplementasikan logika untuk validasi dan penyimpanan perubahan.
3. Implementasi kontrol akses untuk memastikan hanya penulis yang dapat mengedit cerita mereka.

**Comment by rorre** [comment]
Resolved https://github.com/ReadVerseRPL/ReadVerse/commit/c60f4b649a91085c4701312cbe2bbf2e7759ed05
